### ISSUE TITLE
Error in "fa_autoscaling_specs" UAT variable

### ISSUE THREAD

**Issue by antoniocapizzi95** [pagopa/cstar-infrastructure#599]
At line 467 of file "src/k8s/subscriptions/UAT-CSTAR/terraform.tfvars" there is an error, I wrote "famsenrollemnt" instead of "famsenrollment".

**Comment by GiovanniMancini** [comment]
@antoniocapizzi95 Could you add a task in jira and propose a fixing pr? Thank you
